sudo: required
language: minimal
services:
- docker
env:
  matrix:
  - ISC_PRODUCT=ensemble DOCKER_IMAGE=daimor/intersystems-$ISC_PRODUCT:$DOCKER_TAG
  - ISC_PRODUCT=cache DOCKER_IMAGE=daimor/intersystems-$ISC_PRODUCT:$DOCKER_TAG
  global:
  - ISC_BUILD=2017.1.3.317.0
  - DOCKER_TAG=2017.1
branches:
  except:
  - master
install:
- "./download.sh"
- |
  docker run -d --name ftpd_server --rm \
    -e FTP_USER_NAME=user \
    -e FTP_USER_PASS=user \
    -e FTP_USER_HOME=/opt/ftp \
    -v `pwd`/ftp:/opt/ftp \
    --network host \
    stilliard/pure-ftpd
script:
- |
  docker build \
    --network host \
    --build-arg product=$ISC_PRODUCT \
    --build-arg version=$ISC_BUILD \
    -t $DOCKER_IMAGE \
    .
after_success:
- docker stop ftpd_server
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
- docker push $DOCKER_IMAGE
