sudo: required
language: generic
services:
- docker
env:
  global:
  - ISC_BUILD=2018.1.2.609.0
  - DOCKER_TAG=2018.1
  - ISC_PRODUCT=IRIS 
  - DOCKER_IMAGE=daimor/intersystems-iris:$DOCKER_TAG
branches:
  except:
  - master
install:
- "./download.sh"
script:
- docker build --build-arg product=$ISC_PRODUCT --build-arg version=$ISC_BUILD -t $DOCKER_IMAGE .
after_success:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
- docker push $DOCKER_IMAGE
