sudo: required
language: generic
services:
- docker
env:
  matrix:
  - ISC_PRODUCT=ensemble DOCKER_IMAGE=daimor/intersystems-$ISC_PRODUCT:$DOCKER_TAG
  - ISC_PRODUCT=cache DOCKER_IMAGE=daimor/intersystems-$ISC_PRODUCT:$DOCKER_TAG
  global:
  - ISC_BUILD=2017.2.1.801.0
  - DOCKER_TAG=2017.2
branches:
  except:
  - master
install:
- "./download.sh"
script:
- docker build --build-arg product=$ISC_PRODUCT --build-arg version=$ISC_BUILD -t $DOCKER_IMAGE .
after_success:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
- docker push $DOCKER_IMAGE
